### ISSUE TITLE
[feature request]: make Yaml a optional package

### ISSUE THREAD

**Issue by shyim** [neutomic/neutomic#7]
**Is your feature request related to a problem? Please describe.**

 not really. would just reduce the dependencies that are required. 

**Describe the solution you'd like**

Only use the YamlFileLoader, when the Yaml class is there

**Comment by azjezz** [comment]
I think it is nice to have the yaml package by default. ( it is used in the skeleton: https://github.com/neutomic/skeleton/blob/main/config/http.yaml )

I don't see any real issues that having the yaml package introduces, or any actual benifits from removing it.
